from math import ceil
#we dont really care about pi here, we dont ever need to calculate the area
#calculating the ratio of the pizzas is enough to make the code work. 
 
def display_welcome_menu():
    """
    (void) -> void
    
    displays the welcome menu
    
    >>>display_welcome_menu()
    Welcome to the COMP 202 fair pizza calculator!
    Please chose one of the following modes:
    A. "Quantity mode"
    B. "Price mode"
    """
    print('''Welcome to the COMP 202 fair pizza calculator!
Please chose one of the following modes:
A. "Quantity mode"
B. "Price mode"\n''')
    
def get_fair_quantity(big_pizza,small_pizza):
    """
    (num,num) -> int
    
    calculates the amount of small pizzas that have a pizza area equal or greater than 1 big pizza
    
    >>>get_fair_quantity(1,2)
    4
    >>>get_fair_quantity(2,1)
    4
    >>>get_fair_quantity(4.5,4.6)
    2
    """
    if small_pizza>big_pizza:
        small_pizza, big_pizza=big_pizza, small_pizza
    return ceil(big_pizza**2/small_pizza**2)
 
def get_fair_price(big_pizza,big_price,small_pizza,small_amount):
    """
    (num,num,num,int)-> float
    
    Calculates the price per area of big pizza and calculates the total area of small pizza ordered
    returns the price for the given amound of pizza area ordered with 2 deciam places.
    
    >>>get_fair_price(1,1,1,1)
    1.0
    >>>get_fair_price(1,0,1,1)
    0.0
    >>>get_fair_price(14,10.99,6,3)
    6.06
    """
    total_small_pizza_area=small_pizza**2*small_amount
    price_per_area=big_price/big_pizza**2
    price_total=price_per_area*total_small_pizza_area
    return round(price_total,2)
 
def button_A():
    """
    (void) -> void
    Runs the Quantity mode in run_pizza_calculator
    asks for inputs and prints value generated by get_fair_quantity
    
    >>>button_A()
    You selected "Quantity mode"
 
    Enter the diameter of the large pizza: input(1)
    Enter the diameter of the small pizza: input(1)
 
    To be fully satisfied you should order 1 small pizzas
    
    >>>button_A()
    You selected "Quantity mode"
 
    Enter the diameter of the large pizza: input(2)
    Enter the diameter of the small pizza: input(1)
 
    To be fully satisfied you should order 4 small pizzas
    
    >>>button_A()
    You selected "Quantity mode"
 
    Enter the diameter of the large pizza: input(5.2)
    Enter the diameter of the small pizza: input(5.1)
 
    To be fully satisfied you should order 2 small pizzas
    """
    #This only executes in line 170-171 , this is here just to make program more readable.
    print('You selected "Quantity mode"\n')
    large_pizza=float(input("Enter the diameter of the large pizza: "))
    small_pizza=float(input("Enter the diameter of the small pizza: "))
    print('\nTo be fully satisfied you should order '+str(get_fair_quantity(large_pizza,small_pizza))+' small pizzas')
    
def button_B():
    """
    (void) -> void
    
    Runs the Price mode in run_pizza_calculator
    asks for inputs and prints value generated by get_fair_price
    
    >>>button_B()
    You selected "Price mode"
    Enter the diameter of the large pizza: 1
    Enter the price of the large pizza: 1
    Enter the diameter of the small pizza: 1
    Enter the number of small pizzas you'd like to buy: 1
    The fair price to pay for 1.0 small pizzas is $1.0
    
    >>button_B()
    You selected "Price mode"
    Enter the diameter of the large pizza: 1
    Enter the price of the large pizza: 0
    Enter the diameter of the small pizza: 1
    Enter the number of small pizzas you'd like to buy: 1
    The fair price to pay for 1.0 small pizzas is $0.0
    
    >>button_B()
    You selected "Price mode"
    Enter the diameter of the large pizza: 14
    Enter the price of the large pizza: 10.99
    Enter the diameter of the small pizza: 6
    Enter the number of small pizzas you'd like to buy: 3
    The fair price to pay for 1.0 small pizzas is $6.06
    """
    #This only executes in line 172-173, this is here just to make program more readable.
    print('You selected "Price mode"')
    big_pizza=float(input("Enter the diameter of the large pizza: "))
    big_pizza_price=float(input('Enter the price of the large pizza: '))
    small_pizza=float(input('Enter the diameter of the small pizza: '))
    small_amount=int(input('Enter the number of small pizzas you\'d like to buy: '))
    print('The fair price to pay for '+str(small_amount)+' small pizzas is $'+str(get_fair_price(big_pizza,big_pizza_price,small_pizza,small_amount)))
    
    
def run_pizza_calculator():
    """
    (void) -> void
    
    Asks user for the mode of operation. Asks for inputs and puts the inputs in get_fair_price and get_fair_quantity
    in order to perform the calculation for the user.
    
    >>>run_pizza_calculator()
    Welcome to the COMP 202 fair pizza calculator!
    Please chose one of the following modes:
    A. "Quantity mode"
    B. "Price mode"
    input(A)
    -> progran runs button_A() [ view line 57 ]
    
    >>>run_pizza_calculator()
    Welcome to the COMP 202 fair pizza calculator!
    Please chose one of the following modes:
    A. "Quantity mode"
    B. "Price mode"
    input(B)
    -> progran runs button_A() [ view line 68 ]
    
    >>>run_pizza_calculator()
    Welcome to the COMP 202 fair pizza calculator!
    Please chose one of the following modes:
    A. "Quantity mode"
    B. "Price mode"
    input(1)
    This mode is not supported
    """
    display_welcome_menu()
    button=input()
    if button=="A":
        button_A()
    elif button=="B":
        button_B()
    else:
        print("This mode is not supported")